// <auto-generated />
using System;
using Augustine.Senators.WebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Augustine.Senators.WebApi.Migrations
{
    [DbContext(typeof(SenatorsContext))]
    partial class SenatorsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Augustine.Senators.WebApi.Entities.Senator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("District");

                    b.Property<string>("Name");

                    b.Property<string>("Party");

                    b.Property<DateTime?>("TermEndDate");

                    b.Property<DateTime?>("TermStartDate");

                    b.HasKey("Id");

                    b.ToTable("Senators");
                });
#pragma warning restore 612, 618
        }
    }
}
